### ISSUE TITLE
Slide contents are empty after page 6

### ISSUE THREAD

**Issue by Contextualist** [hiroppy/fusuma#110]
I tried version 1.5.0 with a set of slides that used to work at version 1.1.2.

I used a _single_ `.md` file for slides. All slides after page 6 displayed no content, that is, for example:

```
<section class="aligncenter slide current" id="section-7" style="">
::before
<div></div>
::after
</section>
```

The pages were still exist, and all CSS and js still worked, but there's only an empty `div` for each page. The issue seems to happen on any `.md` file that contains more than 6 pages.

Notably, when using `fusuma start`, the initial load suffers from the issue, but if I modify the slide `.md` file and it does dynamic update, the contents are back. When I refresh the page, the contents are gone again. If I do `fusuma build`, the bundled js file contains all of my contents, but nothing get rendered in browser after page 6.

**Comment by galeone** [comment]
I'm facing the same issue

**Comment by hiroppy** [comment]
ok, I'll investigate this issue. Could you submit an example slide?

**Comment by hiroppy** [comment]
And could you try to change from `class` to `className`?

**Comment by hiroppy** [comment]
Please check my slide because I'm not sure what your slides.

https://github.com/hiroppy/fusuma/pull/113

slide: https://hiroppy.github.io/fusuma/issues/index.html#slide=1

```md
https://github.com/hiroppy/fusuma/issues/110

# 1

---

# 2

---

# 3

---

# 4

---

# 5

---

# 6

---

# 7
```

It looks good to me.

**Comment by galeone** [comment]
This is the presentation I'm writing right now and it is the one that has the same behavior described by @Contextualist 
[sample.zip](https://github.com/hiroppy/fusuma/files/3316777/sample.zip)

**Comment by hiroppy** [comment]
@galeone Thank you for submitting your slides. I'm going to investigate asap.

**Comment by galeone** [comment]
Than you @hiroppy - hope you are able to replicate the issue and fix it (or suggest us a workaround in the meantime, so we can continue writing the slides :-) )

**Comment by hiroppy** [comment]
Hey guys, I fixed this issue and published as v1.5.1. Could you try it?

**Comment by galeone** [comment]
It works like a charm!

What was the problem?

**Comment by hiroppy** [comment]
I forgot to turn off the lazyload option.😞
https://github.com/hiroppy/fusuma/commit/900d245f730b393ab7c91b8ac78af13468640f40#diff-b726d3cdf6669b67f96664b33431bbc7

I'll turn on this option when mdx will be stable.(in fusuma, mdx is a little of unstable)

**Comment by galeone** [comment]
I see. Well spotted and thank you for the quick fix.
Now I can go back to my slide creation. Thank you again for this amazing tool :D

**Comment by hiroppy** [comment]
Thank you;) In addition, I'll release a new version tomorrow.
In addition, I implemented an action's timeline and recording feature. https://github.com/hiroppy/fusuma/pull/111

Don't miss it!

**Comment by hiroppy** [comment]
I'll close this issue. Thanks!
