### ISSUE TITLE
MathJax integration?

### ISSUE THREAD

**Issue by galeone** [hiroppy/fusuma#112]
Hi, thank you for this awesome tool!

I'm trying to add some math inside the presentation I'm creating and since I'm used to using LaTeX I'd like to embed MathJax ( https://www.mathjax.org/ ) inside the bundle.

I've tried by updating the `.fusumarc.yml` file as follows, but with no luck:

```yaml
extends:
  js: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
```

So, how can I integrate MathJax inside the slides, so I can just type
```
$$ latex formula $$
```
and get it displayed correctly?

Thanks

**Comment by hiroppy** [comment]
fm, I don't think it doesn't execute when you specify the URL because I don't set `webpackIgnore: true`.

https://github.com/webpack/webpack/issues/8341

**Comment by hiroppy** [comment]
@galeone Could you try the module at your local like a file protocol?

**Comment by galeone** [comment]
Perhaps is too complex, since MathJax is not designed to work well as a node module.

I've tried by placing the Javascript file locally (and all the other required js files), and it loads correctly. However, it is not able to parse the page and render the LaTeX equations.

I fallback using images in the meantime

**Comment by hiroppy** [comment]
How about this? https://github.com/wko27/react-mathjax
Fusuma provides mdx, so you can use react components.

**Comment by uetchy** [comment]
Adding first-class support for LaTeX Math syntax is something yearning for those who make academic slides.
I would like to work on this if you give the go-ahead.

**Comment by hiroppy** [comment]
I don't use LaTex so I don't know use-case but if someone wants to this feature, I'll merge it.:)


@uetchy Could you try it?

**Comment by galeone** [comment]
I'm not a node/js developer (and I'm out of the loop of the new JS framework/components like react/mdx/...) but I'd love to have this feature in fusuma - @uetchy if you work on this it will be great

**Comment by uetchy** [comment]
Digging into it a little while, I've just realized there is an upcoming version of MathJax ([MathJax v3](https://github.com/mathjax/mathjax-v3)). Turned out that MathJax v3 is so nice that it works smoothly on both Node.js and browsers. That is a great match for Fusuma!

I made a working example of TeX to SVG conversion using MathJax v3 `beta.4` published on npm. It looks simpler than the current version and yes, no external dependency!
[![Edit MathJax v3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mathjax-v3-vwffw?fontsize=14)

However, to adopt that version of MathJax, we have to wait a couple of time when it is released😐

**Comment by uetchy** [comment]
Also, suppose we already have support, where should we put this on?
I did a quick search and found that `babelrc.js` contains` Prism.js` dependencies, but not sure if it is a suitable place for MathJax as well.
https://github.com/hiroppy/fusuma/blob/604d42128224ca365c5f244c521ce65a6cb22c2b/packages/configs/src/babelrc.js#L20-L28

**Comment by hiroppy** [comment]
@uetchy  Thank you for investigation. Could you explain how to use MathJax in the slide? For example, MathJax is in only inline-block(`code-block`) or not?
And do we have to convert from md to svg?

**Comment by uetchy** [comment]
MathJax is basically just a LaTeX notation but only for mathematics. And it usually comes with `$` or `$$` like Markdown's code-blocks `` ` `` and ` `` `. So there are both inline and block notation available.
MathJax will extract them and convert it into SVG or HTML.

`$ \sum^N_i x_i $` is inline notation
 ![](https://math.now.sh?inline=\sum^N_ix_i)

`$$ \sum^N_i x_i $$` is block notation
![](https://math.now.sh?from=\sum^N_ix_i)

One of the examples of the combination of Markdown and MathJax is [this article](https://raw.githubusercontent.com/uetchy/uechi.io/master/_posts/2019-01-14-padsize.md) (rendered result is [here](https://uechi.io/blog/padsize)).

There are three options we have:
1. Replace math equations with SVG
2. Replace math equations with PNG (external or data scheme) which is converted from SVG
3. Replace math equations with image tags such that `src` is of equation converter's URL such as [Math API](https://math.now.sh)

What do you think of the options?
@hiroppy

**Comment by hiroppy** [comment]
Thank you for the explanation! fm, I prefer 1. Or can we convert to base64, because if MathJax code is small, we might be better to insert javascript directly?

**Comment by hiroppy** [comment]
I implemented this on #124.

**Comment by uetchy** [comment]
@hiroppy That was so nice!
PR includes [KaTeX](https://katex.org/) which is one alternative to MathJax and it's still ok because both libraries are fast and reliable for production use.

**Comment by galeone** [comment]
Great! I'm adding some comments to the PR

**Comment by hiroppy** [comment]
If you aren't satisfied with LaTex(e.g. syntax, etc...), please reopen this issue.
