### ISSUE TITLE
drop webSlides or not

### ISSUE THREAD

**Issue by hiroppy** [hiroppy/fusuma#141]
## Info

- Operating System: N/A
- Node Version: N/A
- Browser Name and Version: N/A

## Type

- [ ] bug
- [x] feature request

### What is the motivation or use-case for the feature?

WebSlides has many issues.

- no active
- use `window` instance so we cannot set slides more than 2 in the same screen
- performance issue

**Comment by hiroppy** [comment]
I wanna ask @Quramy about this issue as feedback.

**Comment by hiroppy** [comment]
If we change to reveal, we won't be able to scroll the slide to the bottom.

And, styles will be changed like below.

<img width="393" alt="Screen Shot 2019-07-05 at 16 54 08" src="https://user-images.githubusercontent.com/3367801/60733698-8e45a700-9f45-11e9-8973-20b68324d053.png">

**Comment by hiroppy** [comment]
A sample is here. https://deploy-preview-142--heuristic-davinci-1cf783.netlify.com/

**Comment by Quramy** [comment]
> we won't be able to scroll the slide to the bottom

:cry:

**Comment by hiroppy** [comment]
In fact, we'll be able to scroll if we can modify css, but reveal.js doesn't have a responsive design, just zoom.

**Comment by Quramy** [comment]
> reveal.js doesn't have a responsive design

Do you plan to provide responsive customized CSS ? I like the current fusuma’s style. 

I don’t remember how customizable reveal’s css is.  At least, in my opinion, it looks too tough to customize webslides .css(it’s built from scss) .

**Comment by hiroppy** [comment]
Yes or No, I tried to customize CSS for SP, but it is difficult for me. See https://deploy-preview-142--heuristic-davinci-1cf783.netlify.com/#/

Reveal doesn't expand top and bottom, just scaling.

**Comment by hiroppy** [comment]
Updating Information.

- no active
- ~~use window instance so we cannot set slides more than 2 in the same screen~~
  - yes, reveal doesn't use window maybe, but if we put 2 slides on the same screen, an other slide won't work 
- performance issue

**Comment by vivaxy** [comment]
reveal.js is not active too.
