### ISSUE TITLE
Does fusuma support inserting images?

### ISSUE THREAD

**Issue by beizhedenglong** [hiroppy/fusuma#145]
## Info

- Operating System:
- Node Version:
- Browser Name and Version:

## Type

- [ ] bug
- [ ] feature request

**Comment by hiroppy** [comment]
```
![](./image.img)
```

**Comment by beizhedenglong** [comment]
@hiroppy It doesn't seem to work. see this repo  https://github.com/beizhedenglong/fusuma-imgs.  
After run `yarn start`,  the img was not found.

**Comment by hiroppy** [comment]
Fusuma supports just **webp**.
