### ISSUE TITLE
Making webpack plugins addable

### ISSUE THREAD

**Issue by yamatatsu** [hiroppy/fusuma#152]
Would you have plans to make webpack config extendable or webpack plugin addable?
Or, does it not match fusuma's policy "zero config" ?

## Type

- [ ] bug
- [x] feature request

### What is the motivation or use-case for the feature?

I wanna add plugins for using monaco-editor on fusuma.
https://github.com/microsoft/monaco-editor-webpack-plugin

Thanks!

**Comment by hiroppy** [comment]
Nope, I'll implement extending webpack.config.js feature.

**Comment by hiroppy** [comment]
@yamatatsu Which one do you like either cli(--webpack ?) or .fusumarc? I think `.fusumarc` is better because you can omit CLI flag every time.

**Comment by yamatatsu** [comment]
Great!! So fast!! Thanks!!

I think `.fusumarc` is better, too.
Because there is original config system `.fusumarc` already.
I think it is good that one config-file maps whole configurations.

**Comment by hiroppy** [comment]
OK, thanks. I'll release this feature shortly!

**Comment by hiroppy** [comment]
I've just released this feature. thanks. https://github.com/hiroppy/fusuma/releases/tag/v1.13.0
