### ISSUE TITLE
Can't see images loaded from a local images folder

### ISSUE THREAD

**Issue by galeone** [hiroppy/fusuma#198]
## Info

- Operating System: Archlinux
- Node Version: v12.10.0
- Browser Name and Version: Chromium  76.0.3809.132-1

## Type

- [x] bug
- [ ] feature request

### Expected Behavior

I should visualize the images when I create new slides that use images from a local `images` folder - but instead, all I got are 404 error (see screenshot).
### Actual Behavior

I can't visualize the images, the server gives 404.

![Screenshot_20190907_103927](https://user-images.githubusercontent.com/8427788/64472274-fdb16000-d15b-11e9-92ef-4f13ef9d72d9.png)

### How can we reproduce the behavior?

```
# create a new project
npx fusuma init
# create a slides and images folder
mkdir slides
mkdir images
# Put a random image inside the images folder
wget "http://university.it/image/2017/04/reece.JPG?w=800&m=widen" -O images/image.jpg

# Create a simple slide that includes an image from
echo "![](/images/image.jpg" > slides/0-first.md

# Start fusuma in DEVELOPMENT mode
npx fusuma start
```

Perhaps this is not a bug and there is something wrong with my project structure, but I can't see where the problem is.

Thank you for this great project!

**Comment by hiroppy** [comment]
Sorry for the late reply.

```diff
- echo "![](/images/image.jpg" > slides/0-first.md
+ echo "![](/images/image.jpg)" > slides/0-first.md
```

?

**Comment by galeone** [comment]
Yes, sure! It was a typo.

By the way, right now (using the latest version) the workflow I have to follow to have the images inside the presentation is to:

```
fusuma build
cp -r images dist/
```

Only in this way I can have the images when the web application is built.

But when I use `fusuma start` there is no way to see the images

**Comment by hiroppy** [comment]
Thank you for the information! I'll investigate this issue:)

**Comment by heavenshell** [comment]
Same problem here.

1-intro.mdx
```md
🙆‍♂  <img src="../images/profile.jpg" />
🙅‍♂  ![profile](/images/profile.jpg)
```

```
npx fusuma start
```
markdown image did not render to browser.

**Comment by hiroppy** [comment]
I would like to fix but I'm quite busy now... maybe I'll be back from the 10th of October. sorry...
