### ISSUE TITLE
Slides not appearing Presenter Mode

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [hiroppy/fusuma#289]
This seems to be very similar to #139 , expect that one has apparently been solved. I'm having the same error on both Firefox and Chromium.

This **only happens on the online demo pages**, if I install fusuma via npm, locally everything works.

## Info

- Operating System: Linux Mint 19.2
- Node Version: ?
- Browser Name and Version: Firefox 81.0.2

## Type

- [x ] bug
- [ ] feature request

## For Bugs
Opening the [default demo](https://hiroppy.github.io/fusuma/intro/#slide=34) slides and clicking on presentation mode

### Expected Behavior
The other opened window shows the presentation

### Actual Behavior
The presentation flashes for one second and then is permanently white

### How can we reproduce the behavior?
Opening the default slides and clicking on presentation mode. See attached gif:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17727737/99451421-2c929c80-28f0-11eb-9bee-f97b3191d096.gif)

### Full error on presentation window:
Uncaught (in promise) Error: Couldn't find the webslides container!
    e https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:54
    slide https://hiroppy.github.io/fusuma/intro/main.5.c9cb3e47d408f9f88d02.bundle.js:1
    l https://hiroppy.github.io/fusuma/intro/main.5.c9cb3e47d408f9f88d02.bundle.js:1
    i https://hiroppy.github.io/fusuma/intro/main.5.c9cb3e47d408f9f88d02.bundle.js:1
    Zi https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:32
    ja https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:32
    Yo https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:32
    Xo https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:32
    Il https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:32
    Ol https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:32
    Tl https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:32
    el https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:32
    sa https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:32
    e https://hiroppy.github.io/fusuma/intro/main.5.c9cb3e47d408f9f88d02.bundle.js:1
    c https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:11
    _invoke https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:11
    t https://hiroppy.github.io/fusuma/intro/vendor.9.7adff5a5ec9ebcb60c01.bundle.js:11
    m https://hiroppy.github.io/fusuma/intro/main.5.c9cb3e47d408f9f88d02.bundle.js:1
    c https://hiroppy.github.io/fusuma/intro/main.5.c9cb3e47d408f9f88d02.bundle.js:1
vendor.9.7adff5a5ec9ebcb60c01.bundle.js:54:7648

**Comment by hiroppy** [comment]
Thanks, and sorry for the late reply. I'll confirm this issue!

**Comment by hiroppy** [comment]
This issue was fixed, thanks
