### ISSUE TITLE
package goes through rebuild

### ISSUE THREAD

**Issue by epogrebnyak** [hiroppy/fusuma#299]
## Info

- Operating System: Windows
- Node Version: v14.15.1.

##

When I type an npx command the whole package seems to go through rebuild as below: 

```
λ npx fusuma -V
[#.................] / loadDep:@babel/plugin-syntax-optional-chaining: sill resolveWithNewModule @babel/helper-wrap
```

Is there a way to prevent such behaviour on Windows? Probably not an issue with fusuma, but a more general/upstream issue.

**Comment by hiroppy** [comment]
sorry for the late reply. I'm refactoring now so this issue will be fixed.

**Comment by hiroppy** [comment]
This issue was fixed, thanks!
