### ISSUE TITLE
Can't render mermaid diagram

### ISSUE THREAD

**Issue by jcayzac** [hiroppy/fusuma#389]
## Info

- Fusuma Version: 2.5.0
- Operating System: macOS 11.2
- Node Version: 15.6.0

## Type

- [x] bug
- [ ] feature request

## For Bugs

Fusuma shows an error when I use this mermaid graph:

```mermaid
gitGraph:
options
{
  "nodeSpacing": 150,
  "nodeRadius": 10
}
end
commit
branch newbranch
checkout newbranch
commit
commit
checkout master
commit
commit
merge newbranch
```

### Expected Behavior

No error, same rendering as show [here](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2l0R3JhcGg6XG5vcHRpb25zXG57XG4gIFwibm9kZVNwYWNpbmdcIjogMTUwLFxuICBcIm5vZGVSYWRpdXNcIjogMTBcbn1cbmVuZFxuY29tbWl0XG5icmFuY2ggbmV3YnJhbmNoXG5jaGVja291dCBuZXdicmFuY2hcbmNvbW1pdFxuY29tbWl0XG5jaGVja291dCBtYXN0ZXJcbmNvbW1pdFxuY29tbWl0XG5tZXJnZSBuZXdicmFuY2hcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9).

### Actual Behavior

Error:

<img width="488" alt="Screen Shot 2021-02-18 at 17 28 47" src="https://user-images.githubusercontent.com/106682/108327983-6769e080-720f-11eb-8d54-b0f5fdb665af.png">

**Comment by jcayzac** [comment]
I'm also getting errors for [entity relationship diagrams](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram).

**Comment by jcayzac** [comment]
@hiroppy you're missing some escaping somewhere I think. This works:

```chart
gitGraph:
options
&#x7b;
  &#x22;nodeSpacing&#x22;: 150,
  &#x22;nodeRadius&#x22;: 10
&#x7d;
end
commit
branch newbranch
checkout newbranch
commit
commit
checkout master
commit
commit
merge newbranch
```

**Comment by jcayzac** [comment]
Without escaping `{`, `}` and `"` it fails with the error above.

**Comment by hiroppy** [comment]
I reproduced it. yep, this is a bug of fusuma.

**Comment by hiroppy** [comment]
it works! I'll modify the style and release it as patch!

<img width="927" alt="Screen Shot 2021-02-18 at 18 41 11" src="https://user-images.githubusercontent.com/3367801/108337901-fe876600-7218-11eb-8569-50f913a3fe20.png">

**Comment by jcayzac** [comment]
Thank you !
