### ISSUE TITLE
Non-standard mermaid language for markdown code fences

### ISSUE THREAD

**Issue by jcayzac** [hiroppy/fusuma#390]
## Info

- Fusuma Version: 2.5.0
- Operating System: 11.2
- Node Version: 15.6.0

## Type

- [ ] bug
- [x] feature request

### What is the motivation or use-case for the feature?

Most markdown renderers (VS.Code preview, GitLab, Bitbucket etc) recognize the `mermaid` language on a code fence and will correctly render the content using Mermaid. By using the non-conventional `chart` instead, fusuma breaks that flow.

It would be nice if you could support `mermaid`, even just as an alias to `chart`.

**Comment by hiroppy** [comment]
thanks, good point. I'll add the `mermaid` alias.

**Comment by hiroppy** [comment]
closed by https://github.com/hiroppy/fusuma/commit/dd4a940be47febbd020ecc7b0b928f519def7872. thanks.
