### ISSUE TITLE
fragments don't work on last slide

### ISSUE THREAD

**Issue by freder** [hiroppy/fusuma#424]
fragments don't work on last slide

## Info

- Operating System: macos
- Node Version: v15.11.0
- Browser Name and Version: chrome 89.0.4389.82
- fusama: 2.7.0

## Type

- [x] bug
- [ ] feature request

### Expected Behavior

they should work

### Actual Behavior

they don't work

### How can we reproduce the behavior?

```html
fragments:

<!-- fragments-start -->

only work

when there is

a following slide

<!-- fragments-end -->



<!--

---

uncomment me!

-->

```

**Comment by hiroppy** [comment]
I reproduced it, I'll fix it.
