### ISSUE TITLE
production server does not work

### ISSUE THREAD

**Issue by freder** [hiroppy/fusuma#425]
running `fusuma start-prod` opens:

![image](https://user-images.githubusercontent.com/724844/110670097-4f153200-81cd-11eb-8d48-47b61197296d.png)

## Info

- Operating System: macos
- Node Version: v15.11.0
- Browser Name and Version: chrome 89.0.4389.82

## Type

- [x] bug
- [ ] feature request

**Comment by hiroppy** [comment]
Please submit reproducible repo, my local can't repro it.

**Comment by freder** [comment]
seems to have fixed itself. not sure what happened.
