### ISSUE TITLE
video files not found, when using dev server

### ISSUE THREAD

**Issue by freder** [hiroppy/fusuma#427]
- videos work in the _deployed_ presentation
- but not when using the dev server (`fusuma start`)

## Info

- Operating System: macos
- Node Version: v15.11.0
- Browser Name and Version: chrome 89.0.4389.82

## Type

- [x] bug
- [ ] feature request

### Expected Behavior

video should load

### Actual Behavior

browser gets a 404 error for video file

### How can we reproduce the behavior?

```html
images work: ![](../assets/image.jpg)

---

but videos don't:

<video
	src="../assets/my-cool-video.mp4"
	preload=""
	controls
>
</video>
```

**Comment by hiroppy** [comment]
yes, now fusuma doesn't accept the ext. I'll add mp4 soon.
