### ISSUE TITLE
sidebar false in config but appears anyway

### ISSUE THREAD

**Issue by dastasoft** [hiroppy/fusuma#457]
- Operating System: Linux Mint 20.1
- Node Version: v15.12.0
- Browser Name and Version: Google Chrome Version 89.0.4389.90

### Expected Behavior

When sidebar is set as false in .fusumarc.yml no sidebar is displayed on the web.

### Actual Behavior

The burger icon with sidebar still appears.

### How can we reproduce the behavior?

Install Fusuma version 2.8.1 and directly with the contents provided in the fusuma init perform a start of the project.

**Comment by hiroppy** [comment]
thanks, I've fixed this issue and released fusuma as 2.8.2

**Comment by dastasoft** [comment]
Tested with v2.8.2 and now is working fine!

Thanks :+1:
