### ISSUE TITLE
Code Syntax Highlighting not working above v2.6.0

### ISSUE THREAD

**Issue by dastasoft** [hiroppy/fusuma#458]
- Operating System: Linux Mint 20.1
- Node Version: v15.12.0
- Browser Name and Version: Google Chrome Version 89.0.4389.90

### Expected Behavior

syntax highlighting for javascript blocks with configuration by default.

### Actual Behavior

Appears without any syntax highlighting.

### How can we reproduce the behavior?

I've tried with v2.7.0 and v2.8.1 and it's not working, but with version 2.6.0 it's okay, I tested directly with the init project.

Thanks!

**Comment by hiroppy** [comment]
yeah, thank you for reporting. I've known this issue since I introduced to infer lang feature. I'll consider this solution soon.

**Comment by tshemeng** [comment]
@hiroppy  test on v2.8.3 default template, syntax highlighting not working.

**Comment by hiroppy** [comment]
oh, I'll check it. Thank you for reporting.

**Comment by hiroppy** [comment]
@tshemeng it seems working on fusuma@2.8.3.

**Comment by Zomboid999** [comment]
> 
> 
> @tshemeng it seems working on fusuma@2.8.3.

Hello. Everything seems to work except syntax hightlighting in Version 2.8.4. 
-> Is this a known issue?

Thanks for help :)
