### ISSUE TITLE
Samples are gone?

### ISSUE THREAD

**Issue by jcayzac** [hiroppy/fusuma#545]
Hi,
The Samples/ directory doesn't exist anymore?

**Comment by hiroppy** [comment]
Hi, I moved them to `packages/playground` 

https://github.com/hiroppy/fusuma/tree/master/packages/playground

**Comment by jcayzac** [comment]
Thanks! I got scared :)

**Comment by jcayzac** [comment]
@hiroppy I followed a link from the docs website and it got me a 404. I don't remember where exactly but maybe some links still point to old sample locations.

**Comment by szotsaki** [comment]
The link is at the bottom of the [introductory how-to page](https://hiroppy.github.io/fusuma/docs/getting-started/creating-your-slide).
