### ISSUE TITLE
Syntax highlight is not applied

### ISSUE THREAD

**Issue by Quramy** [hiroppy/fusuma#69]
I write markdown's codeblock with triple backquots syntax, but code syntax highlight(prism.js) is not applied 😭 

[![Image from Gyazo](https://i.gyazo.com/1f8e9c626e6ad60fb22665be364fa189.png)](https://gyazo.com/1f8e9c626e6ad60fb22665be364fa189)

**Comment by hiroppy** [comment]
I've released v1.1.0 for fixing this issue.
