### ISSUE TITLE
Webpack fails silently

### ISSUE THREAD

**Issue by Contextualist** [hiroppy/fusuma#72]
When the slides markdown files contains some special unicode (e.g. 'LINE SEPARATOR' (U+2028)), running `fusuma build` fails to produce `dist` but gives no error message. Here's the [minimal config](https://gist.github.com/Contextualist/bb35a70900666e78fe00b89fa576a852) to reproduce the issue.

When the Webpack fails to produce `dist`, the output is slightly different:
<details>
  <summary>failed build</summary>

```
> fusuma build
⠸ Building with webpack...
 name                                              size

 vendors~Sidebar.0.aed4840a479f8e5e2d21.css        2KB

 vendors~Sidebar.0.aed4840a479f8e5e2d21.bundle.js  21KB

 main.1.22876470900cdcabfa5c.bundle.js             1KB

 presenter.view.2.5132d0396839d37f0b6a.bundle.js   3KB

 runtime.ca4ad943b08809522e0f.bundle.js            3KB

 target-blank.4.79a165a01f590bba09f8.bundle.js     350B

 vendor.5.a8049b981193aad902ec.css                 50KB

 vendor.5.a8049b981193aad902ec.bundle.js           295KB
```

</details>

<details>
  <summary>successful build</summary>

```
> fusuma build
⠴ Building with webpack...
 name                                                   size

 vendors~Sidebar.0.1f2b00e54e756ff905c4.css             2KB

 vendors~Sidebar.0.1f2b00e54e756ff905c4.bundle.js       21KB

 main.1.5c3c7e25d57919879b3d.css                        1KB

 main.1.5c3c7e25d57919879b3d.bundle.js                  2KB

 presenter.view.2.1e37ec8b16c663dd4f3e.bundle.js        3KB

 runtime.c460292bd6ca1fc2ab0b.bundle.js                 3KB

 target-blank.4.2610674694803ee1de9e.bundle.js          350B

 vendor.5.f8e08ab36e14ea146a6b.css                      50KB

 vendor.5.f8e08ab36e14ea146a6b.bundle.js                295KB

 index.html                                             1KB

 precache-manifest.8d63c1ce1903a214048640b9190b8a98.js  721B

 service-worker.js                                      1005B
```

</details>

**Comment by hiroppy** [comment]
Thank you for reporting.

hmm.. webpack doesn't have this error. (err is `null`)
https://github.com/hiroppy/fusuma/blob/master/src/webpack/index.js#L15

Anyway, I'll investigate this issue.

**Comment by hiroppy** [comment]
This issue is occurred by terser.
https://github.com/hiroppy/fusuma/blob/master/src/webpack/webpack.prod.config.js#L30-L32

**Comment by hiroppy** [comment]
See https://github.com/terser-js/terser/issues/218

**Comment by hiroppy** [comment]
this issue is resolved by mdx. https://github.com/hiroppy/fusuma/releases/tag/v1.2.0
