### ISSUE TITLE
Create multi column layout without HTML

### ISSUE THREAD

**Issue by tuxflo** [hiroppy/fusuma#75]
At first thanks for your work, fusuma looks great and fits my needs so far.
However I think it should be possible to write multi column slides with markdown only. Its not convenient to write most of the slides in Markdown and then use HTML to write some slides with 2-column layout. Maybe it would be possible to parse some custom markdown elements like | symbols to setup a markdown only 2 column layout?

**Comment by hiroppy** [comment]
Thank you for the suggestion. So do you have any idea how to implement it because Markdown is less expressive?

**Comment by hiroppy** [comment]
I've released a new version and it has mdx. https://github.com/hiroppy/fusuma/releases/tag/v1.2.0
