### ISSUE TITLE
Way to render mark down in HTML elements?

### ISSUE THREAD

**Issue by cuyu** [hiroppy/fusuma#76]
Hi, is there a way to render mark down in the HTML elements? For example:

```html
<div class="grid">
  <div class="column">
    <img src="../images/xxx.png">
  </div>
  <div class="column">
    <div class="markdown">
      ## We can write markdown here
      - xxx
      - xxx
      - xxx
    </div>
  </div>
</div>
```

**Comment by hiroppy** [comment]
Hi, Fusuma uses [markdown-loader](https://github.com/peerigon/markdown-loader) and maybe it doesn't convert this case. If you want to convert this case, please submit an issue to markdown-loader.

**Comment by hiroppy** [comment]
I've released a new version and it has mdx. So, I hope to resolve this problem. https://github.com/hiroppy/fusuma/releases/tag/v1.2.0
