### ISSUE TITLE
[feature request] :emoji: support 

### ISSUE THREAD

**Issue by Quramy** [hiroppy/fusuma#92]
Hi @hiroppy , thanks for the awesome product :) I’m loving to make presentations with fusuma!

I think it’s better that fusuma would render from `:smile:`  to 😄 like GitHub md or slack emoji features. How about this?

And, of course, I’ll contribute about this feature if you would want ;)

**Comment by hiroppy** [comment]
Good idea. Do you know a library to convert `:smile:` to 😄 ?

**Comment by hiroppy** [comment]
And, currently, I've been working to support `.mdx`. So it is also possible with the library of react.

**Comment by Quramy** [comment]
Yeah, I know you’re planning to mdx. 
So, if we’re support emoji, it should be available with md and mdx.

**Comment by Quramy** [comment]
About convert libs or something to load with under webpack build process, I’ll investment them :bow:

I want to discuss how to implement this feature because  you’re the specialist webpack ;)

**Comment by hiroppy** [comment]
@Quramy How about remark-emoji? https://mdxjs.com/advanced/plugins

**Comment by Quramy** [comment]
Looks like with us, I’ll check it out!

**Comment by hiroppy** [comment]
ok, I'll merge `.mdx`, plz wait a moment :)

**Comment by Quramy** [comment]
I got it!
